[package]
name = "Examples"
version = "0.0.0"

[addresses]
hello_blockchain = "_"

[dev-addresses]
hello_blockchain = "0xA"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', subdir = 'aptos-move/framework/aptos-framework', rev = 'mainnet' }

